
advanced:

#  -  name: diffusion_head
#     settings:
#         scan_layers: layers

#  -  name: uncond_diffusion_head
#     settings:
#         scan_layers: layers

 -  name: self
    settings:
        activation_checkpoint_layers:
         - DiffusionHead
        activation_barrier_layers:
         - DiffusionHead

 -  name: encoder_model
    settings:
        activation_checkpoint_layers:
         - EncoderModelLayer
        optimization_barrier_layers:
         - EncoderModelLayer
        scan_layers: layers
        offload_tensors:
         - encoder_model_input

 -  name: decoder_model
    settings:
        activation_checkpoint_layers:
         - DecoderModelLayer
        optimization_barrier_layers:
         - DecoderModelLayer
        scan_layers: layers
        offload_tensors:
         - decoder_model_input
