defaults:
 - llama
 - _self_

# Compile the sequence of decoder layers at `model.layers` using scan.
scan_layers: layers

offload_tensors:
 - decoder_input

apply_to_modules:
 - encoder
 - generator
 - decoder