activation_checkpoint_layers:
 - LlamaDecoderLayer
 - ZRMEncoderLayer

# Refer to https://github.com/pytorch/xla/issues/6379 for backward optimization barrier info.
optimization_barrier_layers:
 - LlamaDecoderLayer
 - ZRMEncoderLayer
