defaults:
  - _self_  # refers to this config file
  - sharding: llama-fsdp  # refers to sharding/llama-fsdp.yaml
  - remat: llama-scan-offload  # refers to remat/llama-scan.yaml


model_id: smollm2-test
model_class: llama.LlamaForCausalLM  # Used to import the model from this class

pretrained_model: null
pretrained_step: null

vocab_size: 49152
bos_token_id: 0
eos_token_id: 0
pad_token_id: 49152

hidden_size: 128
num_hidden_layers: 5

num_attention_heads: 4
num_key_value_heads: 2

intermediate_size: 256
hidden_act: silu

max_position_embeddings: 2048
rope_theta: 10000.0

attention_dropout: false
attention_bias: false

initializer_range: 0.02
rms_norm_eps: 1.0e-05

pad_attention_bias_value: -100.0

# choose attention_kernel from: [flash_attention, splash_attention, null]
attention_kernel: flash_attention
